# Copyright (c) 2023, Bennett Samowich <bennett@foolean.org>
# All rights reserved
# SPDX short identifier: BSD-3-Clause
---

# We put the entire role in a block so we can create
# a role specific tag, which saves the caller from
# having to do so in their playbook.
- name: Role foolean/redhat
  block:

    - name: CIS | Register RedHat system and add subscription
      become: true
      community.general.redhat_subscription:
        activationkey: "{{ redhat_activation_key }}"
        org_id: "{{ redhat_org_id }}"
        state: "{{ redhat_subscription_state }}"
      when:
        - ansible_distribution == "RedHat"
        - redhat_activation_key != "fix-me" and redhat_org_id != "fix-me"

    - name: CIS | Ensure gpgcheck is globally activated
      become: true
      ansible.builtin.lineinfile:
        path: '/etc/dnf/dnf.conf'
        regexp: "^gpgcheck="
        line: 'gpgcheck=1'

    - name: CIS | Ensure system-wide crypto policy is not legacy (check)
      become: true
      ansible.builtin.command:
        cmd: "update-crypto-policies --show"
      register: crypto_policy
      changed_when: false
      failed_when: false
      check_mode: false

    - name: CIS | Ensure system-wide crypto policy is not legacy (set)
      become: true
      ansible.builtin.command:
        cmd: "update-crypto-policies --set {{ redhat_crypto_policy }}"
      when:
        - crypto_policy.stdout != redhat_crypto_policy

  # This block is only applicable to RedHat based systems
  when:
    - ansible_os_family == "RedHat"

  # Tags to be applied to this role (block)
  tags:
    - 'role_foolean_redhat'
